export enum PieceColor {
  WHITE = "WHITE",
  BLACK = "BLACK",
}
export const initialBoard = [
  { name: "rook", color: PieceColor.WHITE, position: "a1" },
  { name: "knight", color: PieceColor.WHITE, position: "b1" },
  { name: "bishop", color: PieceColor.WHITE, position: "c1" },
  { name: "queen", color: PieceColor.WHITE, position: "d1" },
  { name: "king", color: PieceColor.WHITE, position: "e1" },
  { name: "bishop", color: PieceColor.WHITE, position: "f1" },
  { name: "knight", color: PieceColor.WHITE, position: "g1" },
  { name: "rook", color: PieceColor.WHITE, position: "h1" },
  { name: "pawn", color: PieceColor.WHITE, position: "a2" },
  { name: "pawn", color: PieceColor.WHITE, position: "b2" },
  { name: "pawn", color: PieceColor.WHITE, position: "c2" },
  { name: "pawn", color: PieceColor.WHITE, position: "d2" },
  { name: "pawn", color: PieceColor.WHITE, position: "e2" },
  { name: "pawn", color: PieceColor.WHITE, position: "f2" },
  { name: "pawn", color: PieceColor.WHITE, position: "g2" },
  { name: "pawn", color: PieceColor.WHITE, position: "h2" },
  { name: "rook", color: PieceColor.BLACK, position: "a8" },
  { name: "knight", color: PieceColor.BLACK, position: "b8" },
  { name: "bishop", color: PieceColor.BLACK, position: "c8" },
  { name: "queen", color: PieceColor.BLACK, position: "d8" },
  { name: "king", color: PieceColor.BLACK, position: "e8" },
  { name: "bishop", color: PieceColor.BLACK, position: "f8" },
  { name: "knight", color: PieceColor.BLACK, position: "g8" },
  { name: "rook", color: PieceColor.BLACK, position: "h8" },
  { name: "pawn", color: PieceColor.BLACK, position: "a7" },
  { name: "pawn", color: PieceColor.BLACK, position: "b7" },
  { name: "pawn", color: PieceColor.BLACK, position: "c7" },
  { name: "pawn", color: PieceColor.BLACK, position: "d7" },
  { name: "pawn", color: PieceColor.BLACK, position: "e7" },
  { name: "pawn", color: PieceColor.BLACK, position: "f7" },
  { name: "pawn", color: PieceColor.BLACK, position: "g7" },
  { name: "pawn", color: PieceColor.BLACK, position: "h7" },
];
